# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-05 08:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format; '+999999999'. Upto 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('contact_name', models.CharField(max_length=50)),
            ],
        ),
    ]
